### ISSUE TITLE
Cannot install latest version from master brach

### ISSUE THREAD

**Issue by abalabokhin** [SpellholdStudios/BP-BGT-Worldmap#55]
I tried to install the latest version of the mod from master branch and it failed with the error:

```
ERROR: [bp-bgt-worldmap/language/a7tileconv_WORLDMAP_LARGE/WORLDMAP_LARGE.mos] has size 63121524: TOO BIG FOR WEIDU (max 16777211)
ERROR: error loading [bp-bgt-worldmap/language/a7tileconv_WORLDMAP_LARGE/WORLDMAP_LARGE.mos]
```

I used one of the previous commits, e.g. state after commit 0ceaf8a256911ca496 works fine for me.

**Comment by Roberciiik** [comment]
Could you post WeiDU.log? What WeiDU version are you using?

**Comment by abalabokhin** [comment]
The version is 24900. I will post weidu log later when I am back home, but it is not very informative.

I was installing Russian language if it matters. I also should probably mention that I am installing the mod using windows intaller and wine under linux. I can try with native linux weidu but I double it will make the difference (the installations with wine worked well so far).

**Comment by Roberciiik** [comment]
Ok, so this error message is showing up when installing using 32-bit WeiDU executable. You could try to install the mod using 64-bit WeiDU version and/or 64-bit Wine application. 

You can also try to set line 359 in lib/a7_tools.tpa to : `       COPY_LARGE ~%mbc_file%~ ~%output_path%~` to copy large files instead of loading and coping small files. If this works, I will submit a ticket to the tileconv tool repo.
